---
version: "3"

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  SERVER_DIR: "{{.PROJECT_DIR}}/server"

includes:
  ansible: .taskfiles/ansible.yml
  format: .taskfiles/format.yml
  packer: .taskfiles/packer.yml
  pre-commit: .taskfiles/pre-commit.yml
  terraform: .taskfiles/terraform.yml
