---
- hosts:
    - pihole
  become: true
  tasks:
    - name: Disable password login
      user:
        name: debian
        password_lock: true
    - name: Install pi-hole
      ansible.builtin.command: curl -sSL https://install.pi-hole.net | bash
