apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:TAgSQfRzlX4C,iv:bYY7IlzHl90DeR4KlHahCay8p/8++1IBr2R0SY30/gk=,tag:nrmp66+bIQl4IoL6D5rGvA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:hFZjv2m/VzlCh34VqlTiSirgPA==,iv:uGrf6vBsPeQ20ZXUjkPmbFOQQWI8+NoOGsyda3Gis2Q=,tag:qw6fTnXat85mRsX5eWNVug==,type:str]
    SECRET_ALERT_MANAGER_SLACK_WEBHOOK: ENC[AES256_GCM,data:r1Vl1fjZuJR1YKTT+onQ3LQb6RRv8GzLaqc5GIKWL/ZjNrYkhi7wQD6qHGjL3pxPl1WuOlf6ljpWB69PsfhyZFGMek/oQSRA4azGBrPo1WaF,iv:EBAdusbwoZQk44N6/Glqvvvrk30Y6txO9W4POPD/q8g=,tag:gP+marn0CDgrXNeUKo9zrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-28T07:06:57Z"
    mac: ENC[AES256_GCM,data:/dlIVbC8VAAFoBx6C9vPKHc+kptf+86DRX2qRA2TUXDbacxB5k3WGZ4sK23YEy+hibioK+9KlHLKmwYMSUKi8tSTP4QFCKl2xs1vujW4r9XEhNORva6+HHBGcTILl7/dsESunT4NUcR9HzWDmGhYDT9mnqtajiQ7GXYRIuV4jCw=,iv:ECMikAHpmibyXxVyrFwn5t2jDlSh37d5+486t1S0jnA=,tag:PmQWPlpGEyclqfvPz1X+1g==,type:str]
    pgp:
        - created_at: "2021-09-28T07:06:57Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7u9ZptfG2LzAQ/+Ig/GtXIMIlj+cmRIue+wt76KpHw/cJOo2z02a2+XBvYR
            /6hBgRrsSIB9CSGwABcyY0Z2k/ClyLk5ocrbrODrGPABv9Us1mHdXKqwhEJWzUYF
            vpUoC6BIIxc15a2l9RVJbNtT7rZ8ibGVMlt1o9gMa/MoMuVLdXFQyOx2J6o2nIzD
            u3gl6dQTWrDRnkPwlPl48w8ugEVLs5sCgnZPqWmKYYNvAkmVbbHPnxCR7xekosHu
            tf6NsPOIhb7F9Mk4KYZAfplyJlYBdC6Ywnj+Sql3IahqsRicIeQbpd7JGYCj97r2
            3Vi1sqtVwTcuYGPnVHRMQIiEhjncsvAYiEF9i8rXAw6IRlNJ+M96Uf8HiEw8lzyM
            yURkss/VzgiX24mcp/WjHcELpeupVTLH3lcU/t51sZWfleZgIPSqkUKVomq/undF
            ZPp2lcO32e1cvThb/2Ul80XCKMoxOFLcXtMVMrOmq8pdLVs64aYTFg4rU6r8CgVU
            kbCcM1Kk8H3WsJHwTblAvUs2kdopKStK8L0w277alLPxZT4ak1qDLgGN/xfWpl9l
            E5SZbvoCMq3FIGWdrwx4Vhqc6HrK8NaKUoKIjh7OU+xkdpN1U74V6Ri7lCS+CtQd
            08SWsxgZm4fpigY0Y4rTaO3rm/3HUPXtUXTmdY8hMmMk5/wLwH7juuYahXcYRfDU
            aAEJAhWbeP/l9aXYruAq8YfAG89ujj+lqVaslrBTK9o684pKixGOqb5PqWSK/9cm
            JNWHBH+pmqowU6/XfYxxuVRPEMlbKJyz9jsN6RA+H2RHmcOJ+NERBFSp50FV/gqS
            dUHLbt3Z1c97
            =5+IZ
            -----END PGP MESSAGE-----
          fp: F87EE91C12866F36C1CC99E88606529B1E68B608
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
