---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ovpn-data
  namespace: networking
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: nfs-client
