---
ignore: |
  *.sops.*
  env/**/*.y*ml
extends: default
rules:
  truthy:
    allowed-values: ["true", "false"]
  comments:
    min-spaces-from-content: 1
  line-length: disable
    # max: 80
    # allow-non-breakable-words: true
    # allow-non-breakable-inline-mappings: true
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  indentation:
    spaces: 2
    indent-sequences: consistent
